name: "Terraform deployment"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  terraform:
    name: "Terraform provision"
    runs-on: ubuntu-latest
    steps:
      #checkout the terraform repo code
      - name: Checkout tf source code
        uses: actions/checkout@v3

      # setup terraform cli
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init
      - name: Terraform Workspace
        run: terraform workspace show